source 'http://rubygems.org'
gem 'sinatra'
gem 'mongo', '~> 1.9'
gem 'bson_ext'
gem 'json'
gem 'sinatra-security'
gem 'houston'
gem 'chartkick'
gem 'aws-sdk', '~> 1.0'
gem 'nokogiri', '~> 1.5.0'
gem 'user_agent_parser'
gem 'activesupport'